spring:
  application:
    name: documentation-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 50
    hibernate:
      ddl-auto: update
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

server:
  port: 8084
  error:
    whitelabel:
      enabled: false
    include-message: always

jwt:
  secret: ${JWT_SECRET:}

usuario:
  service:
    url: ${USUARIO_SERVICE_URL:http://hml-monolito:8080}

monolito:
  url: ${MONOLITO_URL:http://hml-monolito:8080}